build:
  image: node:6.2.1
  working_dir: /code
  volumes:
    - .:/code
    - $SSH_AUTH_SOCK:/ssh-agent
  environment:
    - BUILDKITE_AGENT_ACCESS_TOKEN
    - BUILDKITE_JOB_ID
    - BUILDKITE_BUILD_ID
    - BUILDKITE_BUILD_NUMBER
    - GITHUB_RELEASE_ACCESS_TOKEN
    - DOCKER_HUB_TRIGGER_TOKEN
    - SSH_AUTH_SOCK=/ssh-agent
    - S3_KEY
    - S3_SECRET
    - PRISMIC_HOME_ID
